move-cn/letsmove

mover/NoWillToBreak/code/task2/faucet_coin.move
mover/NoWillToBreak/code/task2/my_coin.move
mover/NoWillToBreak/code/task3/double_rune.move
mover/NoWillToBreak/notes/task2.md
mover/NoWillToBreak/notes/task3.md
mover/NoWillToBreak/readme.md

 task 2&3 finished

---

mover/NoWillToBreak/code/task4/mygame.move
mover/NoWillToBreak/notes/task4.md
mover/NoWillToBreak/notes/task5.md
mover/NoWillToBreak/readme.md

Task 4&5 finished

---

mover/TigerInYourDream/code/task5/swap.move
mover/TigerInYourDream/notes/task5.md
mover/TigerInYourDream/readme.md

task5 swap

---

mover/unpWn4bl3/code/task4/Move.toml
mover/unpWn4bl3/code/task4/sources/game.move
mover/unpWn4bl3/code/task5/Move.toml
mover/unpWn4bl3/code/task5/sources/fauceta.move
mover/unpWn4bl3/code/task5/sources/faucetb.move
mover/unpWn4bl3/code/task5/sources/swap.move
mover/unpWn4bl3/readme.md

且在4bac5959ca374ad97d81be1ebf765e04256180d6内修复了README.md内表格中英文错误的问题

task4, task 5, table fix in README.md

---

mover/galagala/code/task1/hello_world/Move.toml
mover/galagala/code/task1/hello_world/sources/hello_world.move
mover/galagala/code/task2/move_coin/Move.toml
mover/galagala/code/task2/move_coin/sources/ccoin.move
mover/galagala/code/task3/galanft/Move.toml
mover/galagala/code/task3/galanft/sources/galanft.move
mover/galagala/readme.md

task1 & task2 & task3

---

mover/chenjiantu/readme.md

https://devnet.suivision.xyz/txblock/HGCUVkptogKtnJtUnhuywPaCXEeQ7ZMGowTdr8PcMfi4

finish task1

---

mover/aliyan404/code/task1/hello_move.move
mover/aliyan404/readme.md

完成task1(from tintin)

---

mover/tangyuan2323/readme.md

tintinlab tangyuan2323

---

mover/001/readme.md

Revert "Update readme.md"

---

mover/NoWillToBreak/notes/task6.md
mover/NoWillToBreak/readme.md

finish task6

---

mover/CodeChaosConjurer/code/task1.move
mover/CodeChaosConjurer/notes/task1.md
mover/CodeChaosConjurer/readme.md

 1. finish task 1

---

mover/Mulander-J/.gitignore
mover/Mulander-J/code/task2/Move.toml
mover/Mulander-J/code/task2/sources/coin.move
mover/Mulander-J/code/task2/sources/faucet.move
mover/Mulander-J/code/task3/Move.toml
mover/Mulander-J/code/task3/sources/myNFT.move
mover/Mulander-J/code/task6/index.js
mover/Mulander-J/code/task6/package.json
mover/Mulander-J/code/task6/pnpm-lock.yaml
mover/Mulander-J/notes/task002.md
mover/Mulander-J/notes/task003.md
mover/Mulander-J/notes/task006.md
mover/Mulander-J/readme.md

Finish Task2,Task3,Task6

---

mover/ShuiChang2019/code/task1/sources/hello_world.move
mover/ShuiChang2019/readme.md

finished task 1

---

mover/move-student/code/task1/Move.toml
mover/move-student/code/task1/sources/task1.md
mover/move-student/code/task1/sources/task1.move
mover/move-student/code/task2/Move.toml
mover/move-student/code/task2/sources/fauet.move
mover/move-student/code/task2/sources/mycoin.move
mover/move-student/code/task2/sources/task2.md
mover/move-student/code/task3/Move.toml
mover/move-student/code/task3/sources/task3.md
mover/move-student/code/task3/sources/task3.move
mover/move-student/code/task6/package.json
mover/move-student/code/task6/src/index.ts
mover/move-student/code/task6/task6.md
mover/move-student/code/task6/tsconfig.json
mover/move-student/readme.md

提交 task1, task2, task3, task6

---

mover/zsyzqm/code/task2/Move.toml
mover/zsyzqm/code/task2/readme.md
mover/zsyzqm/code/task2/sources/zsyzqm_coin.move
mover/zsyzqm/code/task2/sources/zsyzqm_faucet_coin.move
mover/zsyzqm/code/task3/Move.toml
mover/zsyzqm/code/task3/readme.md
mover/zsyzqm/code/task3/sources/task3.move
mover/zsyzqm/code/task4/Move.toml
mover/zsyzqm/code/task4/readme.md
mover/zsyzqm/code/task4/sources/task4.move
mover/zsyzqm/readme.md

完成task 2 3 4

---

mover/MartinYeung5/code/task5/Move.toml
mover/MartinYeung5/code/task5/sources/task5.move
mover/MartinYeung5/code/task6/app/page.tsx
mover/MartinYeung5/code/task6/next-env.d.ts
mover/MartinYeung5/code/task6/next.config.mjs
mover/MartinYeung5/code/task6/package.json
mover/MartinYeung5/code/task6/postcss.config.mjs
mover/MartinYeung5/code/task6/tailwind.config.ts
mover/MartinYeung5/code/task6/tsconfig.json
mover/MartinYeung5/readme.md

完成 task6 及 task5

---

mover/Luozzedc/code/sdk/index.ts
mover/Luozzedc/code/sdk/package.json
mover/Luozzedc/code/task5/Move.toml
mover/Luozzedc/code/task5/sources/swap.move
mover/Luozzedc/notes/readme.md
mover/Luozzedc/readme.md

完成task 5 6

---

mover/applesline/code/task6/.gitignore
mover/applesline/code/task6/package-lock.json
mover/applesline/code/task6/package.json
mover/applesline/code/task6/src/task6.ts
mover/applesline/code/task6/tsconfig.json
mover/applesline/readme.md

init && complete task6

---

mover/Serlight/code/task2/source/meepo_faucet.move
mover/Serlight/code/task5/doc.md
mover/Serlight/code/task5/move.toml
mover/Serlight/code/task5/sources/swaper.move
mover/Serlight/readme.md

Task5 swap contract

---

mover/croal99/code/task_02/faucetcoin/sources/faucetcoin.move
mover/croal99/code/task_02/faucetcoin/tests/faucetcoin_tests.move
mover/croal99/code/task_02/my coin/sources/my_coin.move
mover/croal99/code/task_02/my coin/tests/task_02_tests.move
mover/croal99/code/task_02/readme.md

编写利用Sui Move单元测试模块（sui::test_scenario）对独享所有权和共享所有权的进行测试的方法

编写Sui Move单元测试对独享所有权和共享所有权的测试的方法

---

mover/goldpumpkin/code/task2/faucet_coin/sources/faucetcoin.move
mover/goldpumpkin/code/task2/faucet_coin/tests/faucet_coin_tests.move
mover/goldpumpkin/code/task4/README.md
mover/goldpumpkin/code/task4/game/Move.lock
mover/goldpumpkin/code/task4/game/Move.toml
mover/goldpumpkin/code/task4/game/sources/game.move
mover/goldpumpkin/code/task4/game/sources/game_counter.move
mover/goldpumpkin/code/task4/game/tests/game_tests.move
mover/goldpumpkin/readme.md

- 重新发布 Task2，并添加 unit test
- 完成 Task4

finish Task4

---

mover/yjshi2015/readme.md

0xc4301a727914c051c987331f30d002ef907f6f6e4badfec8981e6275ed22486c
thx~  make sui more better!

finish translate move-book

---

mover/yjshi2015/readme.md

Complete translation of reference

---

mover/1pzq/code/task3/my_nft/sources/kite.move
mover/1pzq/code/task4/game/Move.lock
mover/1pzq/code/task4/game/Move.toml
mover/1pzq/code/task4/game/sources/facet.move
mover/1pzq/code/task4/game/sources/game.move
mover/1pzq/code/task4/game/tests/game_tests.move
mover/1pzq/code/task5/Move.lock
mover/1pzq/code/task5/Move.toml
mover/1pzq/code/task5/sources/coin_a.move
mover/1pzq/code/task5/sources/coin_b.move
mover/1pzq/code/task5/sources/pzq.move
mover/1pzq/code/task5/tests/swap_tests.move
mover/1pzq/readme.md

完成task4 task5

---

mover/vegetabledogdog/readme.md

sui git task: https://github.com/move-cn/letsmove/discussions/1199
sui pr: https://github.com/MystenLabs/sui/pull/18636

sui git task

---

mover/greyhao/co-learn-2411/readme.md

群内分享学习笔记&外部平台输出学习笔记_共学营

---

mover/smithclkpayphone123456789010/code/task2/My_Coin/Move.lock
mover/smithclkpayphone123456789010/code/task2/My_Coin/sources/prts.move
mover/smithclkpayphone123456789010/notes/task2.md

笔记链接：https://learnblockchain.cn/article/9988

群内分享学习笔记+外部平台输出学习笔记_共学营

---

mover/lizhecome/co-learn-2411/readme.md
mover/lizhecome/notes/00_01_windows_dos_commands.md
mover/lizhecome/notes/00_02_150_linux_commands.md
mover/lizhecome/notes/00_03_vscode_learning.md
mover/lizhecome/notes/00_04_git_github_learning.md
mover/lizhecome/notes/11_move_generics.md

群里分享学习笔记_共学营+对外输出学习笔记_共学营

---

mover/guoying2026/code/task6/my-first-sui-dapp/src/main.tsx
mover/guoying2026/readme.md

task6 Dapp-kit SDK PTB _共学营

---

mover/oliverxl/readme.md

finish task 8
